### PR TITLE
Update versions for new release y'all

### PR DESCRIPTION
**Pull request by IAmATeaPot418**

### CODE REVIEW

**Review by peter-cg — APPROVED** [review]
Ah, sure. Should we just set them to `v1`?

**Comment by IAmATeaPot418** [comment]
Ohhhh I didn't realize v1 was a thing. But wouldn't that tag change and possibly break a few folks?

**Comment by peter-cg** [comment]
> Ohhhh I didn't realize v1 was a thing. But wouldn't that tag change and possibly break a few folks?

It would break them if we broke them I guess. `v1` was Darren's idea as a way to let people "sorta lock" the version. Better than `@main` anyway. 🤷

**Comment by IAmATeaPot418** [comment]
Oh joy. Our branch protection rules (that I asked to put in of course) conflict with the ignore paths in our workflows only when you update the readme.

on:
  pull_request:
    paths-ignore:
      - "**.md"
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"

**Pull request closed without merging**
