### PR TITLE
fix: add scan path parameter closes #37

### LINKED ISSUE #37: Github action parameter to pass --path to command
# New parameter scan_path

## WHAT

 There is no action parameter to pass --path to the tool.  It is also hard coded here: 
 
 https://github.com/endorlabs/github-action/blob/3b36d8f5960ed3ecc5185bd9458406a2885301c2/src/scan.ts#L330
 
 ## Proposal
 
 Add new optional parameter 'scan_path' with a default value of `--path=.`
 
Remove `--path=.` from src/scan.ts#L330

## Summery and Use Case

Monolithic repository support without requiring a build for dependancies that are outside scope for a particular pipeline.

We need the ability to use this action and scan monolithic repositories, without having to build unrelated artifacts.  The current action does not allow us to pass `--path=` parameter to endorctl tool, given it is hardcoded.

By adding a specific parameter with a default value of what was originally set we can update --path with a native github action parameter.

### Example

```
../test-mono-repo
├── app1
│   └── codechange1
├── app2
└── app3
```
Without the ability to pass the `--path` param to the action, endorctl scans from `./test-mono-repo`.  Given a build pipeline only runs for `./test-mono-repo/app1` we can not assume build artifacts for `./test-mono-repo/app2` or `./test-mono-repo/app3` to be present.

### PR DESCRIPTION
**Pull request by RonMallory**

### CODE REVIEW

**Comment by RonMallory** [comment]
Error discovered while testing this change.

`--bazel-targets-query=XXX` is being added to commands that use the default value of `use_bazel` here:

https://github.com/endorlabs/github-action/blob/3b36d8f5960ed3ecc5185bd9458406a2885301c2/action.yml#L140

To resolve this, moving bazel commands inside use_bazel conditional.

**Review by dkourkouzelis — APPROVED** [review]
Looks good to me.

**Comment by IAmATeaPot418** [comment]
Thank for the contribution @RonMallory! Welcome to the team! 

Passes our tests and my manual spot checks on it.

**Comment by IAmATeaPot418** [comment]
@RonMallory do you mind signing the commits? We'll merge this right after.

**Comment by RonMallory** [comment]
@dkourkouzelis  Thank you for the review!

@IAmATeaPot418 recommitted with signed commits!

**Review by IAmATeaPot418 — APPROVED** [review]

**Comment by IAmATeaPot418** [comment]
Wahoo! Thank you @RonMallory!

**Pull request merged**
