### PR TITLE
Add support for SAST

### PR DESCRIPTION
**Pull request by dkourkouzelis**

### CODE REVIEW

**Comment by dkourkouzelis** [comment]
@hghmn not exactly sure why this fails...

**Comment by hghmn** [comment]
@dkourkouzelis I added https://github.com/endorlabs/github-action/pull/66/commits/d04f63f8a071e9c52992b2558427de0bfe7668cb, which updates the versions for node and yarn to match the versions running under setup-node: https://github.com/endorlabs/github-action/actions/runs/11521661050/job/32075812248?pr=66#step:3:10.

With the latest you see any changes in the output under `/dist` after running `yarn run build && yarn run package`?

**Comment by dkourkouzelis** [comment]
Thank you @hghmn! By "latest" do you mean locally for me? I pulled the branch over to get your changes, upgraded yarn to 1.22.22, with node @v22.4.1, ran the above commands and still get diffs. Not sure if this is expected but I will not push them.

**Comment by hghmn** [comment]
> Thank you @hghmn! By "latest" do you mean locally for me? I pulled the branch over to get your changes, upgraded yarn to 1.22.22, with node @v22.4.1, ran the above commands and still get diffs. Not sure if this is expected but I will not push them.

I updated the recommended versions in package.json and CONTRIBUTING.md to match the current version of `node` used by setup-node (20.18.0).

Testing locally with node v22.4.1 I get the same build output as v20.18.0, so I'm not sure where the difference may be coming from in your environment.

**Review by hghmn — APPROVED** [review]

**Comment by dkourkouzelis** [comment]
Me neither. Thank you for the quick review and fix!

**Review by darrenpmeyer — APPROVED** [review]

**Pull request merged**
